### ISSUE TITLE
Last read chapter

### ISSUE THREAD

**Issue by rRoler** [StoicSun/MD-Follow-list#1]
Can you add the last read chapter number of every manga?
Something like this:
![Screenshot 2021-05-14 215250](https://user-images.githubusercontent.com/60528736/118322115-e4e77900-b4fe-11eb-93c3-0c1ae8a4d3af.png)

It might be a little too complicated tho, because [it needs to get the uuid for every read chapter](https://api.mangadex.org/docs.html#operation/get-manga-chapter-readmarkers) as far as I know, but thanks anyways.

**Comment by 5urajdas** [comment]
Hey I added your requested feature but its a pretty bad implementation but you can go ahead and try it. 
I just couldn't get the the csv to update so I had to create a new csv file for the chapter list, not to mention its really slow. 
Thanks for the idea nonetheless.

**Comment by RolerGames** [comment]
Yeah, I expected it to be slow and thanks for doing.
There seems to be a problem when it gets these two manga:
![Screenshot 2021-05-16 001513](https://user-images.githubusercontent.com/60528736/118379714-af18c200-b5dc-11eb-9d7f-590f5f0794c1.png)
As you can see when it just enters a loop and ends the list without getting the rest. 
I'm not sure if this is a script or an API bug tho.

**Comment by RolerGames** [comment]
Yeah, I expected it to be slow and thanks for doing it.
There seems to be a problem when it gets these two manga:
![Screenshot 2021-05-16 001513](https://user-images.githubusercontent.com/60528736/118379714-af18c200-b5dc-11eb-9d7f-590f5f0794c1.png)
As you can see it just enters a loop and ends the list without getting the rest. 
I'm not sure if this is a script bug or an API bug tho.
